2022-11-30 11:43:15,572 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,577 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:43:15,581 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,584 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,590 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,593 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,598 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,603 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,606 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,609 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_password_hashing_is_correct line 50 | 
2022-11-30 11:43:15,612 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,615 |    INFO | server | fnc: is_authorized | args: ({'user': {'username': 'u2', 'password': 'password'}}, {'u2': 'StreamWriter', 'user1': 'StreamWriter'}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function test_user_is_authorized line 74 | 
2022-11-30 11:43:15,615 |    INFO | server | User is already authorized
authorized = {'u2': 'StreamWriter', 'user1': 'StreamWriter'}
2022-11-30 11:43:15,619 |    INFO | server | fnc: get_database_object | args: ('../db.txt',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\tests\test_utils.py | Called from function setUp line 17 | 
2022-11-30 11:43:15,623 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:16,456 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:16,460 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:22,900 |    INFO | server | Connection from ('127.0.0.1', 56968) | waiting authorize
2022-11-30 11:48:22,914 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669798102.900856, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 11:48:22,916 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 11:48:22,918 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 11:48:25,281 |    INFO | server | Client ('127.0.0.1', 56968) wants to quit
2022-11-30 11:48:25,789 |    INFO | server | User "u2" disconnected
2022-11-30 11:48:31,284 | WARNING | server | Server closing
2022-11-30 11:48:46,860 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 11:48:46,865 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 11:48:48,662 | WARNING | server | Server closing
2022-11-30 12:03:00,823 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 13 | 
2022-11-30 12:03:00,826 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:03:03,558 | WARNING | server | Server closing
2022-11-30 12:04:45,332 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 21 | 
2022-11-30 12:04:45,336 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:04:46,747 | WARNING | server | Server closing
2022-11-30 12:05:39,910 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:05:39,915 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:05:45,102 | WARNING | server | Server closing
2022-11-30 12:07:23,343 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:07:23,347 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:07:28,595 |    INFO | server | Connection from ('127.0.0.1', 58064) | waiting authorize
2022-11-30 12:07:28,599 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799248.595521, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:07:28,602 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:07:28,604 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:07:41,431 |    INFO | server | Client ('127.0.0.1', 58064) wants to quit
2022-11-30 12:07:41,947 |    INFO | server | User "u2" disconnected
2022-11-30 12:07:49,226 | WARNING | server | Server closing
2022-11-30 12:13:05,671 |    INFO | server | fnc: get_database_object | args: (WindowsPath('I:/docker_practice/gb_client_server_apps/project/db.txt'),) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\server.py | Called from function <module> line 18 | 
2022-11-30 12:13:05,674 |    INFO | server | Listening at 127.0.0.1:4444
2022-11-30 12:15:20,287 |    INFO | server | Connection from ('127.0.0.1', 58371) | waiting authorize
2022-11-30 12:15:20,290 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799720.286005, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:20,292 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:15:20,294 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:15:29,491 |    INFO | server | Connection from ('127.0.0.1', 58379) | waiting authorize
2022-11-30 12:15:29,493 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799729.490784, 'user': {'password': 'password', 'username': 'u2'}}, {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:15:29,493 |    INFO | server | User is already authorized
authorized = {'u2': <StreamWriter transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>> reader=<StreamReader waiter=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000001AE2378BF70>()]> transport=<_ProactorSocketTransport fd=516 read=<_OverlappedFuture pending overlapped=<pending, 0x1ae237e08b0> cb=[_ProactorReadPipeTransport._loop_reading()]>>>>}
2022-11-30 12:15:29,495 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:16:06,043 |    INFO | server | Client ('127.0.0.1', 58371) wants to quit
2022-11-30 12:16:06,556 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:10,776 |    INFO | server | Client ('127.0.0.1', 58379) wants to quit
2022-11-30 12:16:11,291 |    INFO | server | User "u2" disconnected
2022-11-30 12:16:11,291 |   ERROR | server | Server error | u2 ('127.0.0.1', 58379) has already left
2022-11-30 12:17:11,271 |    INFO | server | Connection from ('127.0.0.1', 58461) | waiting authorize
2022-11-30 12:17:11,273 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799831.271336, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:11,275 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:11,277 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:36,394 |    INFO | server | User "u2" disconnected
2022-11-30 12:17:37,778 |    INFO | server | Connection from ('127.0.0.1', 58484) | waiting authorize
2022-11-30 12:17:37,780 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799857.778999, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:17:37,782 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:17:37,783 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:17:54,789 |    INFO | server | Client ('127.0.0.1', 58484) wants to quit
2022-11-30 12:17:55,292 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:28,265 |    INFO | server | Connection from ('127.0.0.1', 58546) | waiting authorize
2022-11-30 12:19:28,267 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799968.265088, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:28,269 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:28,271 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:19:31,104 |    INFO | server | Client ('127.0.0.1', 58546) wants to quit
2022-11-30 12:19:31,617 |    INFO | server | User "u2" disconnected
2022-11-30 12:19:58,829 |    INFO | server | Connection from ('127.0.0.1', 58578) | waiting authorize
2022-11-30 12:19:58,831 |    INFO | server | fnc: is_authorized | args: ({'action': 1, 'time': 1669799998.829102, 'user': {'password': 'password', 'username': 'u2'}}, {}) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 56 | 
2022-11-30 12:19:58,833 |    INFO | server | fnc: make_secure_password | args: ('password',) | kwargs: {} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function verify_password line 136 | 
2022-11-30 12:19:58,834 |    INFO | server | fnc: generate_response_message | args: (<Status.OK: 200>,) | kwargs: {'message': 'Authorized'} | stated in: I:\docker_practice\gb_client_server_apps\project\utils\utils.py | Called from function handle_request line 57 | 
2022-11-30 12:20:01,391 |    INFO | server | Client ('127.0.0.1', 58578) wants to quit
2022-11-30 12:20:01,898 |    INFO | server | User "u2" disconnected
